# Generated by Django 4.2.4 on 2023-09-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professor', '0002_alter_professor_valor_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('assunto', models.TextField()),
                ('professor', models.ManyToManyField(to='professor.professor')),
            ],
        ),
    ]
