# Generated by Django 4.2.4 on 2023-09-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='carga_horaria',
            field=models.IntegerField(default=1, verbose_name='Carga Horária'),
            preserve_default=False,
        ),
    ]
