# Generated by Django 4.2.4 on 2023-09-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudoProgramatico', '0002_remove_conteudoprogramatico_carga_horaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudoprogramatico',
            name='periodo',
            field=models.CharField(choices=[('P1', 'Turma P1'), ('P2', 'Turma P2'), ('P3', 'Turma P3'), ('P4', 'Turma P4'), ('P5', 'Turma P5'), ('P6', 'Turma P6'), ('P7', 'Turma P7'), ('P8', 'Turma P8')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
