# Generated by Django 4.2.4 on 2023-09-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudoProgramatico', '0003_conteudoprogramatico_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudoprogramatico',
            name='area_do_conteudo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
