# Generated by Django 4.2.4 on 2023-09-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudoProgramatico', '0004_conteudoprogramatico_area_do_conteudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudoprogramatico',
            name='periodo',
            field=models.CharField(choices=[('P1', 'Turma P1'), ('P2', 'Turma P2'), ('P3', 'Turma P3'), ('P4', 'Turma P4'), ('P5', 'Turma P5'), ('P6', 'Turma P6'), ('P7', 'Turma P7'), ('P8', 'Turma P8'), ('P9', 'Turma P9'), ('P10', 'Turma P10')], max_length=3),
        ),
    ]
