# Generated by Django 4.2.4 on 2023-09-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('area_atuacao', models.CharField(max_length=200, verbose_name='Area de Atuação')),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
