# Generated by Django 4.2.4 on 2023-09-02 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conteudoProgramatico', '0003_conteudoprogramatico_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('mensalidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tempo_conclusao', models.IntegerField()),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conteudoProgramatico.conteudoprogramatico')),
            ],
        ),
    ]
