# Generated by Django 4.2.4 on 2023-09-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudoProgramatico', '0004_conteudoprogramatico_area_do_conteudo'),
        ('curso', '0003_alter_curso_mensalidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='conteudo',
        ),
        migrations.AddField(
            model_name='curso',
            name='conteudo',
            field=models.ManyToManyField(to='conteudoProgramatico.conteudoprogramatico'),
        ),
    ]
