# Generated by Django 4.2.4 on 2023-09-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_remove_curso_conteudo_curso_conteudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='tempo_conclusao',
            field=models.IntegerField(verbose_name='Tempo de Conclusão'),
        ),
    ]
