# Generated by Django 4.2.4 on 2023-09-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
