# Generated by Django 4.2.4 on 2023-09-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0002_alter_matricula_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='data_matricula',
            field=models.DateField(auto_now_add=True, verbose_name='Data da Matrícula'),
        ),
    ]
